# Generated by Django 5.2.6 on 2025-11-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='musicas/')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'permissions': [('can_access_radialista', 'Pode acessar o painel do radialista e transmitir')],
            },
        ),
    ]
