# Generated by Django 5.2.6 on 2025-10-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiomaffei', '0002_musica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'permissions': [('can_access_radialista', 'Pode acessar o painel do radialista e transmitir')]},
        ),
    ]
